### ISSUE TITLE
Nice article, a few bugs?

### ISSUE THREAD

**Issue by mikeaustin** [jackfranklin/react-css-modules-webpack#7]
It looks like the repo is correct, but the post has an error:

    loader: ExtractTextPlugin.extract(
      'style-loader',
      combineLoaders([{

I don't think that 'style-loader' should be there. Also, it's a little confusing to use combineLoaders() with only one loader in the production weback:

    loader: ExtractTextPlugin.extract(
      combineLoaders([{
        loader: 'css-loader',
        query: {
          modules: true,
          localIdentName: '[name]__[local]___[hash:base64:5]'
        }
      }])
    )

Last, I see 'options' used instead of 'query' in other blogs for css-loader. Maybe they are synonyms?

Other than that, your article was the shortest, most to-the-point. Others spewed pages and irrelevant information. Good job!

**Comment by jackfranklin** [comment]
Thanks - I think really that I need to write a new version of this post with Webpack 3 + the latest plugins. I'll try to get to that sometime. Or if you'd like to write a new version I'd love to put it on the site (with full credit of course!)
